version: '2'

services:
  rflinkproxy:
    image: ssenart/rflinkproxy:latest
    container_name: rflinkproxy
    restart: always
    network_mode: bridge
    environment:
      - LISTEN_PORT=1234
      - CONNECT_PORT=/dev/ttyUSB0
      - BAUD_RATE=57600
      - RESTART_PERIOD=4
    ports:
      - 1234:1234
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
